apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "tommi.sohlberg@hotmail.com"
    privateKeySecretRef:
      name: le-acme-privatekey-production
    solvers:
    - dns01:
        route53:
          region: us-east-1
          accessKeyIDSecretRef:
            name: "aws-secret"
            key: "awsAccessKeyID"
          secretAccessKeySecretRef:
            name: "aws-secret"
            key: "awsSecretAccessKey"
