apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: homelab
  namespace: default
spec:
  config: '{
            "name":"homelab",
            "type":"ovn-k8s-cni-overlay",
            "cniVersion":"0.3.1",
            "topology":"localnet",
            "netAttachDefName":"default/homelab"
          }'