apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-deployment
spec:
  project: default
  source:
    repoURL: https://github.com/suulperi/homelab.git
    targetRevision: HEAD
    path: gitops/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager-operator
  syncPolicy:
    automated:
      allowEmpty: true