---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-virtualization-operator-deployment
spec:
  project: default
  source:
    repoURL: https://github.com/suulperi/homelab.git
    targetRevision: HEAD
    path: gitops/openshift-virtualization/operator
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-cnv
  syncPolicy:
    automated:
      allowEmpty: true