apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-network-connfigurations
spec:
  project: default
  source:
    repoURL: https://github.com/suulperi/homelab.git 
    targetRevision: HEAD
    path: gitops/vm-network
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      allowEmpty: true