---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-setup
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/suulperi/homelab.git
    targetRevision: HEAD
    path: gitops/argocd-applications
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      allowEmpty: true