---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  availabilityConfig: "Basic"
  overrides:
    components:
    - name: edge-manager-preview
      enabled: true
