apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-helm-repo-manager
rules:
- apiGroups:
  - helm.openshift.io
  resources:
  - helmchartrepositories
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete